package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The generator is data-driven: everything it emits comes from parsing
// codes.go — the const block, AllCodes, and the existing Action/Doc
// switches. These tests assert both the happy path (fixture codespkg)
// and the R-3 parity faults: each fixture under testdata/codespkg-*
// must be refused with an error naming the offending constant.
func TestGenerateCodesHappyPath(t *testing.T) {
	src, err := generateCodes("testdata/codespkg")
	require.NoError(t, err)
	assert.Contains(t, src, "// Code generated by docgen. DO NOT EDIT.")
	// One explicit case per AllCodes code, in AllCodes order.
	alpha := stringsIndex(src, "case CodeAlpha:")
	bravo := stringsIndex(src, "case CodeBravo:")
	require.NotEqual(t, -1, alpha)
	require.NotEqual(t, -1, bravo)
	assert.Less(t, alpha, bravo, "cases must follow AllCodes order")
	// The default arms are re-emitted verbatim from codes.go.
	assert.Contains(t, src, "return ActionBug")
	assert.Contains(t, src, `"unknown code: " + string(c)`)
}

func TestGenerateCodesMissingConstFromAllCodes(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-missing")
	require.Error(t, err, "a declared constant missing from AllCodes must fail generation")
	assert.Contains(t, err.Error(), "CodeBravo", "the error must name the constant")
}

func TestGenerateCodesDuplicateAllCodesEntry(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-dup")
	require.Error(t, err, "a duplicate AllCodes entry must fail generation")
	assert.Contains(t, err.Error(), "CodeAlpha", "the error must name the constant")
}

func TestGenerateCodesUnknownEntryInAllCodes(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-unknown")
	require.Error(t, err, "an AllCodes entry with no declared constant must fail generation")
	assert.Contains(t, err.Error(), "CodeGhost", "the error must name the identifier")
}

func TestGenerateCodesNoExplicitDataFallsToDefault(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-nodata")
	require.Error(t, err, "a code without an explicit Action case must not silently fall to the default arm")
	assert.Contains(t, err.Error(), "CodeBravo", "the error must name the constant")
}

func TestGenerateCodesRealTronParses(t *testing.T) {
	src, err := generateCodes(realTronDir(t))
	require.NoError(t, err, "the real tron/codes.go must satisfy parity and generate")
	assert.Contains(t, src, "case CodeTxDuplicate:")
	assert.Contains(t, src, "case CodeReceiptOutOfEnergy:")
	assert.Contains(t, src, "case CodeRPCMethodFailed:")
}

// stringsIndex is assert-agnostic indexing helper for order checks.
func stringsIndex(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}
