package main

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

const genHeader = `// Code generated by docgen. DO NOT EDIT.
//
// Regenerate:
//	go run github.com/kslamph/tronlib/v2/cmd/docgen generate-codes -pkg ./v2/tron -out ./v2/tron/codes_gen.go

package tron

`

// emitCodesGen renders codes_gen.go from the extracted data: one explicit
// case per AllCodes code, in AllCodes order, for both Action and Doc, plus
// the default arms. Cases are emitted from AllCodes itself, so by
// construction every code gets a case — and checkParity has already refused
// any code without explicit data, so nothing can silently fall to default.
func emitCodesGen(all []string, consts []codeConst, action, doc map[string]string) (string, error) {
	value := make(map[string]string, len(consts))
	for _, c := range consts {
		value[c.Name] = c.Value
	}

	var b strings.Builder
	b.WriteString(genHeader)

	b.WriteString("// Action returns the default remediation for this code class. The case\n")
	b.WriteString("// list is generated from tron.AllCodes; add the constant to AllCodes and\n")
	b.WriteString("// give it explicit Action/Doc cases in codes.go, then regenerate.\n")
	b.WriteString("func (c Code) Action() Action {\n\tswitch c {\n")
	for _, name := range all {
		fmt.Fprintf(&b, "\tcase %s: // %s\n\t\treturn %s\n", name, value[name], action[name])
	}
	b.WriteString("\tdefault: // any future code not yet classified\n\t\treturn ActionBug\n\t}\n}\n")

	b.WriteString("\n")
	b.WriteString("// Doc returns the agent-facing advice line for this code class. This is\n")
	b.WriteString("// the advice table rendered by docgen; remediation language is correct\n")
	b.WriteString("// and expected here (see the layering contract in codes.go). The case\n")
	b.WriteString("// list is generated from tron.AllCodes.\n")
	b.WriteString("func (c Code) Doc() string {\n\tswitch c {\n")
	for _, name := range all {
		fmt.Fprintf(&b, "\tcase %s: // %s\n\t\treturn %s\n", name, value[name], goQuoteDoc(doc[name]))
	}
	b.WriteString("\tdefault:\n\t\treturn \"unknown code: \" + string(c)\n\t}\n}\n")

	// format.Source both validates the syntax and makes the output canonical,
	// so regenerating twice is byte-identical.
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("emitted source does not parse (docgen bug): %w", err)
	}
	return string(src), nil
}

// goQuoteDoc renders a doc line as a Go string literal. Doc lines are
// single-line prose, so the raw literal form is preferred for readability;
// anything that cannot appear raw falls back to strconv.Quote.
func goQuoteDoc(s string) string {
	if strings.ContainsAny(s, "`\r\n") {
		return strconv.Quote(s)
	}
	return "`" + s + "`"
}
