package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The generator is data-driven: everything it emits comes from parsing
// codes.go — the const block, AllCodes, and the existing Action/Doc
// switches. These tests assert both the happy path (fixture codespkg)
// and the R-3 parity faults: each fixture under testdata/codespkg-*
// must be refused with an error naming the offending constant.
func TestGenerateCodesHappyPath(t *testing.T) {
	src, err := generateCodes("testdata/codespkg")
	require.NoError(t, err)
	assert.Contains(t, src, "// Code generated by docgen. DO NOT EDIT.")
	// One explicit case per AllCodes code, in AllCodes order.
	alpha := strings.Index(src, "case CodeAlpha:")
	bravo := strings.Index(src, "case CodeBravo:")
	require.NotEqual(t, -1, alpha)
	require.NotEqual(t, -1, bravo)
	assert.Less(t, alpha, bravo, "cases must follow AllCodes order")
	// The default arms are re-emitted verbatim from codes.go.
	assert.Contains(t, src, "return ActionBug")
	assert.Contains(t, src, `"unknown code: " + string(c)`)
}

func TestGenerateCodesMissingConstFromAllCodes(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-missing")
	require.Error(t, err, "a declared constant missing from AllCodes must fail generation")
	assert.Contains(t, err.Error(), "CodeBravo", "the error must name the constant")
}

func TestGenerateCodesDuplicateAllCodesEntry(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-dup")
	require.Error(t, err, "a duplicate AllCodes entry must fail generation")
	assert.Contains(t, err.Error(), "CodeAlpha", "the error must name the constant")
}

func TestGenerateCodesDuplicateValue(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-dupvalue")
	require.Error(t, err, "two Code constants sharing a value must fail generation")
	assert.Contains(t, err.Error(), "CodeAlpha", "the error must name the first constant")
	assert.Contains(t, err.Error(), "CodeBravo", "the error must name the second constant")
	assert.Contains(t, err.Error(), "same.value", "the error must name the shared value")
}

func TestGenerateCodesUnknownEntryInAllCodes(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-unknown")
	require.Error(t, err, "an AllCodes entry with no declared constant must fail generation")
	assert.Contains(t, err.Error(), "CodeGhost", "the error must name the identifier")
}

func TestGenerateCodesNoExplicitDataFallsToDefault(t *testing.T) {
	_, err := generateCodes("testdata/codespkg-nodata")
	require.Error(t, err, "a code without an explicit Action case must not silently fall to the default arm")
	assert.Contains(t, err.Error(), "CodeBravo", "the error must name the constant")
}

func TestGenerateCodesRealTronParses(t *testing.T) {
	src, err := generateCodes(realTronDir(t))
	require.NoError(t, err, "the real tron/codes.go must satisfy parity and generate")
	assert.Contains(t, src, "case CodeTxDuplicate:")
	assert.Contains(t, src, "case CodeReceiptOutOfEnergy:")
	assert.Contains(t, src, "case CodeRPCMethodFailed:")
}

// TestGeneratedCodesAreAFixedPoint is the self-hosting guard: the committed
// codes_gen.go must be byte-identical to what generateCodes produces from
// the current sources. A mismatch means codes.go was edited without
// regenerating.
//
// Scope boundary: this catches codes.go drift (new constant, AllCodes edit,
// case data edit) made without regenerating. It does NOT catch hand-edits
// to codes_gen.go case data: post-migration this file is both generator
// output and generator input, so any hand-edit is trivially a fixed point.
// Semantic changes to case data are gated by review of this file (DO NOT
// EDIT header) and by the parity check at generation time, which still
// requires every code to have explicit case data.
func TestGeneratedCodesAreAFixedPoint(t *testing.T) {
	committed, err := os.ReadFile(filepath.Join(realTronDir(t), "codes_gen.go"))
	require.NoError(t, err)
	want, err := generateCodes(realTronDir(t))
	require.NoError(t, err, "the real tron package must satisfy parity and generate")
	assert.Equal(t, string(committed), want,
		"codes_gen.go is stale; run: go -C v2 run ./cmd/docgen generate-codes -pkg ./tron -out ./tron/codes_gen.go")
}
