package main

// CLI-level tests for run(), the testable body of main. These pin the exit
// codes and the exact text the user sees, which is what docgen's CI gate
// depends on: a drift check that exits 0 on drift, or a usage error that exits
// 0 instead of 2, would silently disable the gate.

import (
	"bytes"
	"go/parser"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// runCLI invokes run with args and returns the exit code plus what the command
// wrote to each stream.
func runCLI(t *testing.T, args ...string) (code int, stdout, stderr string) {
	t.Helper()
	var out, err bytes.Buffer
	code = run(args, &out, &err)
	return code, out.String(), err.String()
}

func TestRunNoCommandPrintsUsageAndExits2(t *testing.T) {
	code, stdout, stderr := runCLI(t)
	assert.Equal(t, 2, code)
	assert.Empty(t, stdout, "usage errors must not write to stdout")
	assert.Contains(t, stderr, "usage: docgen <command> [flags]")
}

func TestRunUnknownCommandNamesIt(t *testing.T) {
	code, _, stderr := runCLI(t, "frobnicate")
	assert.Equal(t, 2, code)
	assert.Contains(t, stderr, `docgen: unknown command "frobnicate"`)
	assert.Contains(t, stderr, "usage: docgen", "the command list is the fix")
}

func TestRunGenerateCodesRequiresBothFlags(t *testing.T) {
	for _, args := range [][]string{
		{"generate-codes"},
		{"generate-codes", "-pkg", "testdata/codespkg"},
		{"generate-codes", "-out", filepath.Join(t.TempDir(), "x.go")},
	} {
		code, _, stderr := runCLI(t, args...)
		assert.Equal(t, 2, code, "%v", args)
		assert.Contains(t, stderr, "generate-codes requires -pkg and -out", "%v", args)
	}
}

func TestRunSyncDocsRequiresPkgAndDocs(t *testing.T) {
	for _, args := range [][]string{
		{"sync-docs"},
		{"sync-docs", "-pkg", syncFixturePkg(t)},
		{"sync-docs", "-docs", "doc.md"},
	} {
		code, _, stderr := runCLI(t, args...)
		assert.Equal(t, 2, code, "%v", args)
		assert.Contains(t, stderr, "sync-docs requires -pkg and at least one -docs", "%v", args)
	}
}

// TestRunBadFlagFallsToUsage covers the two parse-error branches that
// flag.ExitOnError made unreachable in-process: flag reports the bad flag and
// run appends the command list. The exit code is 2 either way, so the CI
// contract is unchanged; only the extra usage text is new.
func TestRunBadFlagFallsToUsage(t *testing.T) {
	for _, cmd := range []string{"generate-codes", "sync-docs"} {
		code, _, stderr := runCLI(t, cmd, "-bogus", "1")
		assert.Equal(t, 2, code, cmd)
		assert.Contains(t, stderr, "flag provided but not defined: -bogus", cmd)
		assert.Contains(t, stderr, "usage: docgen", cmd)
	}
}

// TestRunHelpExitsZero guards the flag.ErrHelp mapping. Under the old
// flag.ExitOnError, -h exited 0 inside Parse; translating every parse error to
// a usage error would have turned `docgen sync-docs -h` into exit 2.
func TestRunHelpExitsZero(t *testing.T) {
	for _, tt := range []struct{ cmd, flag string }{
		{"generate-codes", "-h"},
		{"sync-docs", "-help"},
	} {
		code, stdout, stderr := runCLI(t, tt.cmd, tt.flag)
		assert.Equal(t, 0, code, "%s %s", tt.cmd, tt.flag)
		assert.Empty(t, stdout)
		assert.Contains(t, stderr, "Usage of "+tt.cmd, "%s %s", tt.cmd, tt.flag)
	}
}

func TestRunGenerateCodesWritesTheGeneratedSource(t *testing.T) {
	out := filepath.Join(t.TempDir(), "codes_gen.go")
	code, stdout, stderr := runCLI(t, "generate-codes", "-pkg", "testdata/codespkg", "-out", out)
	require.Equal(t, 0, code, "stderr: %s", stderr)
	assert.Contains(t, stdout, "docgen: wrote "+out)
	assert.Contains(t, stdout, "bytes)")

	src, err := os.ReadFile(out)
	require.NoError(t, err)
	assert.Contains(t, string(src), "// Code generated by docgen. DO NOT EDIT.")
}

func TestRunGenerateCodesReportsGenerationFailure(t *testing.T) {
	out := filepath.Join(t.TempDir(), "codes_gen.go")
	code, stdout, stderr := runCLI(t, "generate-codes", "-pkg", "testdata/codespkg-missing", "-out", out)
	assert.Equal(t, 1, code, "a generation fault is a failure, not a usage error")
	assert.Empty(t, stdout, "nothing was written, so nothing may claim it was")
	assert.Contains(t, stderr, "docgen: ")
	_, err := os.Stat(out)
	assert.True(t, os.IsNotExist(err), "a failed generation must leave no output file")
}

func TestRunGenerateCodesReportsUnreadablePackage(t *testing.T) {
	code, _, stderr := runCLI(t, "generate-codes", "-pkg", filepath.Join(t.TempDir(), "nope"), "-out", filepath.Join(t.TempDir(), "x.go"))
	assert.Equal(t, 1, code)
	assert.Contains(t, stderr, "no such file or directory")
}

func TestRunGenerateCodesReportsUnwritableOutput(t *testing.T) {
	code, stdout, stderr := runCLI(t, "generate-codes", "-pkg", "testdata/codespkg",
		"-out", filepath.Join(t.TempDir(), "missing-dir", "codes_gen.go"))
	assert.Equal(t, 1, code)
	assert.Empty(t, stdout)
	assert.Contains(t, stderr, "docgen: ")
}

func TestRunSyncDocsWritesAndReportsEachFile(t *testing.T) {
	doc := writeSyncFixture(t, syncDocFixture)
	code, stdout, stderr := runCLI(t, "sync-docs", "-pkg", syncFixturePkg(t), "-docs", doc)
	require.Equal(t, 0, code, "stderr: %s", stderr)
	assert.Contains(t, stdout, "docgen: synced "+doc)

	body, err := os.ReadFile(doc)
	require.NoError(t, err)
	assert.Contains(t, string(body), "| `alpha.one` | `retry` | alpha and bravo doc |",
		"run() must reach the same pipeline the unit tests drive directly")
}

func TestRunSyncDocsCheckExitsOneOnDrift(t *testing.T) {
	// An unsynced fixture is by definition drifted: the table block is empty.
	doc := writeSyncFixture(t, syncDocFixture)
	code, stdout, stderr := runCLI(t, "sync-docs", "-pkg", syncFixturePkg(t), "-docs", doc, "-check")
	assert.Equal(t, 1, code, "-check is the CI gate; drift must be non-zero")
	assert.Empty(t, stdout, "-check writes nothing and must say so")
	assert.Contains(t, stderr, "is stale")
}

func TestRunSyncDocsCheckPassesOnASyncedFile(t *testing.T) {
	doc := writeSyncFixture(t, syncDocFixture)
	code, _, stderr := runCLI(t, "sync-docs", "-pkg", syncFixturePkg(t), "-docs", doc)
	require.Equal(t, 0, code, "stderr: %s", stderr)

	code, _, stderr = runCLI(t, "sync-docs", "-pkg", syncFixturePkg(t), "-docs", doc, "-check")
	assert.Equal(t, 0, code, "a synced file must pass the drift gate: %s", stderr)
}

// TestRunSyncDocsMissingDocsFileExitsOne covers the read failure inside
// runSync's per-file loop as surfaced through the CLI.
func TestRunSyncDocsMissingDocsFileExitsOne(t *testing.T) {
	code, _, stderr := runCLI(t, "sync-docs", "-pkg", syncFixturePkg(t),
		"-docs", filepath.Join(t.TempDir(), "absent.md"))
	assert.Equal(t, 1, code)
	assert.Contains(t, stderr, "no such file or directory")
}

func TestMultiFlagAccumulatesAndJoins(t *testing.T) {
	var m multiFlag
	assert.Equal(t, "", m.String(), "an unset flag renders as the empty string")
	require.NoError(t, m.Set("a.md"))
	require.NoError(t, m.Set("b.md"))
	assert.Equal(t, "a.md,b.md", m.String())
	assert.Equal(t, []string{"a.md", "b.md"}, []string(m), "each -docs occurrence appends")
}

// TestRenderExprFormatsExpressions pins the strings that appear in codesgen's
// rejection messages, so a generated error tells the reader what the source
// actually said.
//
// renderExpr's fallback (fmt.Sprintf("%T", e) when go/format fails) is not
// tested on purpose: go/format panics rather than returning an error for a
// hand-built incomplete node, so there is no reachable way to make it fail. It
// is exercised through its real callers, where the expressions come from a
// parsed file - see TestCheckDefaultArmNamesOffendingExpression.
func TestRenderExprFormatsExpressions(t *testing.T) {
	for _, src := range []string{
		"ActionBug",
		"`unknown code: ` + string(c)",
		"tronpkg.Something",
	} {
		expr, err := parser.ParseExpr(src)
		require.NoError(t, err, src)
		assert.Equal(t, src, renderExpr(expr))
	}
}
