// Command migrate generates the v1 -> v2 migration guide by AST diff
// (spec §14 step 12). It scans v1's public surface and v2's, classifies each
// v1 symbol, and writes the generated tables between the go:migration markers
// in the guide. The guide is generated; the curated Renames/Removed inputs in
// tables.go are reviewed source, never a hand-written table.
//
//	go -C v2 run ./cmd/migrate                  # regenerate docs/migration.md
//	go -C v2 run ./cmd/migrate -check           # fail if it is stale (CI)
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	migStart = "<!-- go:migration -->"
	migEnd   = "<!-- /go:migration -->"
)

func main() {
	v1 := flag.String("v1", "../pkg", "v1 source root to scan (the v1 public surface is under pkg/)")
	v2Root := flag.String("v2-root", ".", "v2 module root")
	out := flag.String("out", "docs/migration.md", "guide path")
	check := flag.Bool("check", false, "report drift instead of writing the guide")
	flag.Parse()

	if err := run(*v1, *v2Root, v2Pkgs, curatedInputs(), *out, *check); err != nil {
		fmt.Fprintln(os.Stderr, "migrate:", err)
		os.Exit(1)
	}
}

// run scans both trees, classifies with the supplied curated inputs, and
// either writes the guide or (check) byte-compares the re-rendered block
// against the file on disk. Inputs is a parameter (not the global curated set)
// so tests can exercise the engine against fixture trees.
func run(v1Root, v2Root string, pkgs []string, in Inputs, out string, check bool) error {
	v1, err := scanTree(v1Root)
	if err != nil {
		return fmt.Errorf("scan v1 %s: %w", v1Root, err)
	}
	var v2 []Symbol
	for _, p := range pkgs {
		dir := filepath.Join(v2Root, p)
		syms, err := scanDir(dir)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("scan v2 %s: %w", dir, err)
		}
		v2 = append(v2, syms...)
	}
	sort.Slice(v2, func(i, j int) bool { return v2[i].Key < v2[j].Key })

	r, err := classify(v1, v2, in)
	if err != nil {
		return err
	}
	body := render(r)

	if check {
		b, err := os.ReadFile(out)
		if err != nil {
			return err
		}
		got, err := fillBlock(string(b), body)
		if err != nil {
			return err
		}
		if got != string(b) {
			return fmt.Errorf("%s is stale; run: go -C v2 run ./cmd/migrate", out)
		}
		return nil
	}

	md := guideTemplate
	if b, err := os.ReadFile(out); err == nil {
		md = string(b)
	}
	got, err := fillBlock(md, body)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(out, []byte(got), 0o644)
}

// fillBlock replaces the content between the go:migration markers, keeping
// both markers on their own lines. Prose outside is untouched.
func fillBlock(md, body string) (string, error) {
	i := strings.Index(md, migStart)
	if i < 0 {
		return "", fmt.Errorf("marker %q not found", migStart)
	}
	j := strings.Index(md[i:], migEnd)
	if j < 0 {
		return "", fmt.Errorf("closing marker %q not found", migEnd)
	}
	j += i
	return md[:i+len(migStart)] + "\n" + body + "\n" + md[j:], nil
}

const guideTemplate = `# tronlib v1 -> v2 migration guide

> Generated by ` + "`cmd/migrate`" + ` from an AST diff against v1's ` + "`pkg/`" + ` surface.
> Regenerate: ` + "`go -C v2 run ./cmd/migrate`" + `; the CI drift gate runs ` + "`./cmd/migrate -check`" + `.
>
> **Unmapped is an honest state**, not "deleted": it means no mechanical v2
> counterpart was found. Reviewers grow the curated ` + "`renames`" + ` table in
> ` + "`cmd/migrate/tables.go`" + ` from that list; they never hand-edit this block.

` + migStart + `

` + migEnd + `
`
