// Code generated by docgen. DO NOT EDIT.
//
// Regenerate (from the repo root):
//	go -C v2 run ./cmd/docgen generate-codes -pkg ./tron -out ./tron/codes_gen.go
//
// To extend the code set: add the constant to the const block and AllCodes
// in codes.go, then hand-add its Action and Doc cases HERE (this file is
// both generated and, post-migration, the data source for regeneration, by
// design); run the Regenerate command. Parity checking fails generation
// until both the constant and its cases exist. Note: this file is both
// generated output and, post-migration, the generator's data source for
// Action/Doc cases — hand-edits to case data are legitimate but
// unreviewable by tooling; they must go through code review.

package tron

// Action returns the default remediation for this code class. The case
// list is generated from tron.AllCodes; see the header for the
// extension workflow.
func (c Code) Action() Action {
	switch c {
	case CodeAmountInvalid: // amount.invalid
		return ActionFixCall
	case CodeAmountTooManyDecimals: // amount.too_many_decimals
		return ActionFixCall
	case CodeAmountOverflow: // amount.overflow
		return ActionFixCall
	case CodeAmountNegative: // amount.negative
		return ActionFixCall
	case CodeAmountDecimalsMismatch: // amount.decimals_mismatch
		return ActionFixCall
	case CodeAddressInvalid: // address.invalid
		return ActionFixCall
	case CodeAddressWrongPrefix: // address.wrong_prefix
		return ActionFixCall
	case CodeTxNoSigner: // tx.no_signer
		return ActionFixTransaction
	case CodeTxAlreadySigned: // tx.already_signed
		return ActionFixCall
	case CodeTxExpired: // tx.expired
		return ActionFixTransaction
	case CodeTxDuplicate: // tx.duplicate
		return ActionWait
	case CodeTxFeeLimitTooLow: // tx.fee_limit_too_low
		return ActionFixTransaction
	case CodeTxInvalidArgument: // tx.invalid_argument
		return ActionFixCall
	case CodeTxUnknownContract: // tx.unknown_contract
		return ActionFixCall
	case CodeTxTaposInvalid: // tx.tapos_invalid
		return ActionFixTransaction
	case CodeTxTooLarge: // tx.too_large
		return ActionFixTransaction
	case CodeChainConnection: // chain.connection
		return ActionRetry
	case CodeChainTimeout: // chain.timeout
		return ActionRetry
	case CodeChainClosed: // chain.closed
		return ActionRetry
	case CodeChainUnavailable: // chain.unavailable
		return ActionRetry
	case CodeChainUnconfirmed: // chain.unconfirmed
		return ActionWait
	case CodeChainNetworkMismatch: // chain.network_mismatch
		return ActionFixCall
	case CodeReceiptReverted: // receipt.reverted
		return ActionFixTransaction
	case CodeReceiptOutOfEnergy: // receipt.out_of_energy
		return ActionFixTransaction
	case CodeReceiptFailed: // receipt.failed
		return ActionFixTransaction
	case CodeContractNotFound: // contract.not_found
		return ActionFixCall
	case CodeContractNoABI: // contract.no_abi
		return ActionFixCall
	case CodeContractBadABI: // contract.bad_abi
		return ActionFixCall
	case CodeContractBadMetadata: // contract.bad_metadata
		return ActionFixCall
	case CodeContractMethodUnknown: // contract.method_unknown
		return ActionFixCall
	case CodeContractArgMismatch: // contract.arg_mismatch
		return ActionFixCall
	case CodeContractResultTypeMismatch: // contract.result_type_mismatch
		return ActionFixCall
	case CodeAccountInsufficientBalance: // account.insufficient_balance
		return ActionFund
	case CodeAccountInsufficientEnergy: // account.insufficient_energy
		return ActionFund
	case CodeAccountInsufficientBandwidth: // account.insufficient_bandwidth
		return ActionFund
	case CodeAccountPermissionDenied: // account.permission_denied
		return ActionFixCall
	case CodeKeyInvalid: // key.invalid
		return ActionFixCall
	case CodeKeyMnemonicInvalid: // key.mnemonic_invalid
		return ActionFixCall
	case CodeRPCMethodFailed: // rpc.method_failed
		return ActionRetry
	default: // any future code not yet classified
		return ActionBug
	}
}

// Doc returns the agent-facing advice line for this code class. This is
// the advice table rendered by docgen; remediation language is correct
// and expected here (see the layering contract in codes.go). The case
// list is generated from tron.AllCodes.
func (c Code) Doc() string {
	switch c {
	case CodeAmountInvalid: // amount.invalid
		return `an amount argument failed validation`
	case CodeAmountTooManyDecimals: // amount.too_many_decimals
		return `the amount has more decimal places than the token allows`
	case CodeAmountOverflow: // amount.overflow
		return `the amount overflows the integer representation`
	case CodeAmountNegative: // amount.negative
		return `a negative amount was supplied`
	case CodeAmountDecimalsMismatch: // amount.decimals_mismatch
		return `the operands have different decimals`
	case CodeAddressInvalid: // address.invalid
		return `the value is not a valid TRON address`
	case CodeAddressWrongPrefix: // address.wrong_prefix
		return `the address's network prefix is not TRON's (0x41)`
	case CodeTxNoSigner: // tx.no_signer
		return `the transaction has no signer attached`
	case CodeTxAlreadySigned: // tx.already_signed
		return `the transaction is already signed`
	case CodeTxExpired: // tx.expired
		return `the transaction's expiration has passed`
	case CodeTxDuplicate: // tx.duplicate
		return `this txid was already broadcast or executed; poll its receipt instead of resending`
	case CodeTxFeeLimitTooLow: // tx.fee_limit_too_low
		return `the fee limit is below the node's minimum`
	case CodeTxInvalidArgument: // tx.invalid_argument
		return `a transaction parameter failed validation`
	case CodeTxUnknownContract: // tx.unknown_contract
		return `the referenced contract type is unknown to the SDK`
	case CodeTxTaposInvalid: // tx.tapos_invalid
		return `the node rejected the transaction's reference block (TAPOS_ERROR)`
	case CodeTxTooLarge: // tx.too_large
		return `the transaction exceeds the node's size limit (TOO_BIG_TRANSACTION_ERROR)`
	case CodeChainConnection: // chain.connection
		return `the node could not be reached`
	case CodeChainTimeout: // chain.timeout
		return `the node did not respond in time`
	case CodeChainClosed: // chain.closed
		return `the connection to the node is closed`
	case CodeChainUnavailable: // chain.unavailable
		return `the node is unavailable (server error or maintenance)`
	case CodeChainUnconfirmed: // chain.unconfirmed
		return `the transaction was broadcast but is not yet confirmed`
	case CodeChainNetworkMismatch: // chain.network_mismatch
		return `the endpoint is on a different TRON network than expected`
	case CodeReceiptReverted: // receipt.reverted
		return `the contract execution reverted`
	case CodeReceiptOutOfEnergy: // receipt.out_of_energy
		return `the transaction exceeded its energy budget; raise fee_limit or stake energy for the account`
	case CodeReceiptFailed: // receipt.failed
		return `the transaction was processed but failed`
	case CodeContractNotFound: // contract.not_found
		return `no contract exists at the given address`
	case CodeContractNoABI: // contract.no_abi
		return `no ABI was provided for the contract`
	case CodeContractBadABI: // contract.bad_abi
		return `the provided ABI could not be parsed`
	case CodeContractBadMetadata: // contract.bad_metadata
		return `the contract's metadata violates the expected layout`
	case CodeContractMethodUnknown: // contract.method_unknown
		return `the method name is not present in the contract ABI`
	case CodeContractArgMismatch: // contract.arg_mismatch
		return `the arguments do not match the method's ABI signature`
	case CodeContractResultTypeMismatch: // contract.result_type_mismatch
		return `the result accessor does not match the ABI return type`
	case CodeAccountInsufficientBalance: // account.insufficient_balance
		return `the account lacks the required balance`
	case CodeAccountInsufficientEnergy: // account.insufficient_energy
		return `the account lacks the energy required for this call`
	case CodeAccountInsufficientBandwidth: // account.insufficient_bandwidth
		return `the account lacks the bandwidth required for this transaction`
	case CodeAccountPermissionDenied: // account.permission_denied
		return `the signer lacks permission for this operation`
	case CodeKeyInvalid: // key.invalid
		return `the private key is not a valid secp256k1 key`
	case CodeKeyMnemonicInvalid: // key.mnemonic_invalid
		return `the mnemonic phrase is invalid`
	case CodeRPCMethodFailed: // rpc.method_failed
		return `the node rejected or failed an rpc; retry with backoff, and if the error repeats identically switch node or method rather than looping`
	default:
		return "unknown code: " + string(c)
	}
}
