package eventtool

import (
	"fmt"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/kslamph/tronlib/v2/event"
)

func keyLiteral(t *testing.T, name string, types []string) string {
	t.Helper()
	k := event.SignatureKey(name, types)
	parts := make([]string, len(k))
	for i, b := range k {
		parts[i] = fmt.Sprintf("0x%02x", b)
	}
	return "{" + strings.Join(parts, ", ") + "}:"
}

func TestGenerateParsesAndCarriesKeys(t *testing.T) {
	ev := SavedEvent{
		Sighash:   hexKey("Ping", []string{"uint256"}),
		Signature: "Ping(uint256)",
		Name:      "Ping",
		Inputs:    []SavedInput{{Type: "uint256", Name: "n"}},
	}
	src, err := Generate([]SavedEvent{ev})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "builtin_gen.go", src, 0)
	if err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}
	if f.Name.Name != "event" {
		t.Fatalf("package = %s, want event", f.Name.Name)
	}
	s := string(src)
	for _, want := range []string{
		"map[[32]byte]*Definition",
		"// Code generated by cmd/eventtool generate",
		`Name: "Ping"`,
		`Type: "uint256"`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
	if !strings.Contains(s, keyLiteral(t, "Ping", []string{"uint256"})) {
		t.Errorf("generated source missing the 32-byte key literal for Ping(uint256)")
	}
}

func TestGenerateIsSortedBySighash(t *testing.T) {
	zed := SavedEvent{Sighash: hexKey("Zed", nil), Signature: "Zed()", Name: "Zed"}
	axe := SavedEvent{Sighash: hexKey("Axe", nil), Signature: "Axe()", Name: "Axe"}
	src, err := Generate([]SavedEvent{zed, axe})
	if err != nil {
		t.Fatal(err)
	}
	lo, hi := axe.Sighash, zed.Sighash
	if lo > hi {
		lo, hi = hi, lo
	}
	if strings.Index(string(src), lo) > strings.Index(string(src), hi) {
		t.Fatal("entries not sorted by sighash; generated diffs would be unstable")
	}
}

func TestGenerateRejectsUnverifiedEntry(t *testing.T) {
	_, err := Generate([]SavedEvent{{Sighash: strings.Repeat("00", 32), Signature: "Ping(uint256)", Name: "Ping"}})
	if err == nil {
		t.Fatal("want an error for a corpus entry whose sighash does not derive from its signature")
	}
}
