package eventtool

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// generateHeader is the file's provenance line. It names the tool and the
// input corpus so a reader can reproduce the file exactly.
const generateHeader = `// Code generated by cmd/eventtool generate from internal/eventdata/events_registry.json. DO NOT EDIT.

// Provenance: this file holds the ecosystem event table (event definitions
// collected from the selected contracts' on-chain ABIs) keyed by the full
// 32-byte keccak-256 of each canonical signature — the registry's key space.
// init() registers every entry insert-if-absent, so built-ins never displace an
// explicit registration. Regenerate with:
//
//	go run ./cmd/eventtool generate

package event
`

// DefaultGeneratedPath is the generated built-in table generate writes.
const DefaultGeneratedPath = "event/builtin_gen.go"

// Generate renders event/builtin_gen.go from a verified corpus. Keys are 32-byte
// array literals (sorted by sighash for stable diffs) and the source is run
// through go/format, replacing v1's hand-rolled bufio emitter.
func Generate(events []SavedEvent) ([]byte, error) {
	sorted := append([]SavedEvent(nil), events...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Sighash < sorted[j].Sighash })

	var b bytes.Buffer
	b.WriteString(generateHeader)
	b.WriteString("\nvar builtinSig = map[[32]byte]*Definition{\n")
	for i := range sorted {
		e := &sorted[i]
		if err := verifyEvent(e); err != nil {
			return nil, err
		}
		key, err := hex.DecodeString(e.Sighash)
		if err != nil || len(key) != 32 {
			return nil, fmt.Errorf("eventtool: entry %s: bad sighash: %v", e.Name, err)
		}
		var parts []string
		for _, kb := range key {
			parts = append(parts, fmt.Sprintf("0x%02x", kb))
		}
		fmt.Fprintf(&b, "\t{%s}: {\n", strings.Join(parts, ", "))
		fmt.Fprintf(&b, "\t\tName: %s,\n", strconv.Quote(e.Name))
		b.WriteString("\t\tInputs: []ParamDef{\n")
		for _, in := range e.Inputs {
			fmt.Fprintf(&b, "\t\t\t{Type: %s, Indexed: %t, Name: %s},\n",
				strconv.Quote(in.Type), in.Indexed, strconv.Quote(in.Name))
		}
		b.WriteString("\t\t},\n\t},\n")
	}
	b.WriteString(`}

func init() {
	defs := make([]*Definition, 0, len(builtinSig))
	for _, def := range builtinSig {
		defs = append(defs, def)
	}
	registerBuiltin(defs)
}
`)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("eventtool: generated source does not format: %w", err)
	}
	return src, nil
}
